### ISSUE TITLE
Feature Request: Fluidd & Mainsail K1 Themes

### ISSUE THREAD

**Issue by Nastras** [Guilouz/Creality-K1-and-K1-Max#38]
Cool design for the Fluidd / Mainsail GUI:
https://github.com/tlace17/Creality_Mainsail_Themes
https://github.com/tlace17/Creality_Fluidd_Themes

**Comment by Guilouz** [comment]
His fluidd theme is not very well designed because it does not allow you to choose the color with the color picker, mine does:

<img width="900" alt="Capture d’écran 2023-09-29 à 23 41 41" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/9b4317d8-a4f3-4fa0-95a7-aa8fb699588a">

<img width="900" alt="Capture d’écran 2023-09-29 à 23 41 53" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/17733a1f-cbcc-40f5-bce0-c69fd74c4382">

<img width="900" alt="Capture d’écran 2023-09-29 à 23 42 12" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/6e67334b-0868-4fa8-9bb1-748bb1e1e84a">

**Comment by tlace17** [comment]
> His fluidd theme is not very well designed because it does not allow you to choose the color with the color picker, mine does:
> 
> <img alt="Capture d’écran 2023-09-29 à 23 41 41" width="900" src="https://user-images.githubusercontent.com/12702322/271725415-9b4317d8-a4f3-4fa0-95a7-aa8fb699588a.png"> <img alt="Capture d’écran 2023-09-29 à 23 41 53" width="900" src="https://user-images.githubusercontent.com/12702322/271725423-17733a1f-cbcc-40f5-bce0-c69fd74c4382.png"> <img alt="Capture d’écran 2023-09-29 à 23 42 12" width="900" src="https://user-images.githubusercontent.com/12702322/271725427-6e67334b-0868-4fa8-9bb1-748bb1e1e84a.png">

I agree, for one reason or another I was having issues figuring out how that functionality works. Nice work getting it to work, I am learning as I go and I saw that nobody had made one yet. What did you have to do to get that to work? My Mainsail themes are a bit more involved but I could probably make them better.

**Comment by Guilouz** [comment]
SVG file must be have no infill and point out to the correct fluidd class.

I will share my theme.

**Comment by tlace17** [comment]
> SVG file must be have no infill and point out to the correct fluidd class.
> 
> I will share my theme.

Thanks! Mine didn't have any infill. I will have to check out what you mean by Fluidd class.

**Comment by Guilouz** [comment]
I'm working on this theme:

<img width="2544" alt="Capture d’écran 2023-10-01 à 01 31 52" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/bb1060ce-352b-45d7-afc4-7806c7cd34a0">

<img width="2542" alt="Capture d’écran 2023-10-01 à 01 34 06" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/89556314-f996-41e3-95fe-a5974bee0e09">

**Comment by Nastras** [comment]
@Guilouz What has actually happened to the topic here? Neither solution has made it into the script yet ☹️.
