### ISSUE TITLE
white and black timelapse

### ISSUE THREAD

**Issue by le-pet** [Guilouz/Creality-K1-and-K1-Max#40]
all is in the title, the timelapse encoding is in white and black, i don't know if it's the setting yuv420p or not

**Comment by Guilouz** [comment]
I have tested them in fluidd and it's working fine for me.``

Make sure you have latest timelapse version i have updated few days ago.

**Comment by BrianP525** [comment]
I am also having this issue. Just performed full install today using the tools provided. (Awesome project btw)  If I export the images, the zip contains all the pictures and they look fine. When it renders, there is a green bar at the bottom right, the colors appear off, looks mostly black and white, but the yellow sticker on the printhead appears as black and white, but you can also see an artifact of this label appear green and squished, but in 2 other areas of the image, one to the left, and another to the right.

![frame000123](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/54ac11e9-16fc-4701-8f89-c204031e1c65)

https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/22acfdcc-596b-498a-b308-9b1a8fb6c017

**Comment by le-pet** [comment]
tested in fluidd and moonraker, same, as described by @BrianP525, updated automatically the script, and in case of manually to, reboted the printer, same, the problem is about 2 of my k1

**Comment by Guilouz** [comment]
Can you try this file after deleting old timelapse.py and timelapse.pyc files from /usr/data/moonraker/moonraker/moonraker/components/

[timelapse.py.zip](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/12778377/timelapse.py.zip)

**Comment by BrianP525** [comment]
Deleted the 2 timelapse.py and .pyc files, uploaded the timelapse.py from the zip, restarted and tested. Still have the same result, pictures are fine, video render is bad. I also found that there is a separate timelapse that records in the creality side of things, that seems to be only accessible through creality print, and that timelapse looks fine.
![frame000040](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/3cc0a032-f2d1-46d5-a750-75dd66946d84)

https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/f9e8811c-9e8e-453f-88ab-b67052cff46d

**Comment by Guilouz** [comment]
Can you try this one:

[timelapse.py.zip](https://github.com/Guilouz/Creality-K1-and-K1-Max/files/12781383/timelapse.py.zip)

**Comment by le-pet** [comment]
the last timelapse.py working good for me, just the quality is bad, and a error MIME in video preview on mainsail 

https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/36859339/921bd3f4-5cab-4568-b189-a1cbed2257e1

**Comment by BrianP525** [comment]
I found a few things with this one.
The video now render's correctly, and colors are correct, no artifacts.
I am able to play it back via fluidd interface, and locally when I download.
As @le-pet mentioned, the quality has significantly decreased. (Photos are still the same when exporting, just the render quality has dropped)

https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/90c08a8b-abb3-41f4-aa9e-e55232a985d6

![frame000046](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/22726974-d266-4df9-aefa-6a9cb5b30cd8)

This file had the park printhead option toggled on by default, I was able to correct by disabling that option in the fluidd settings.

I also noticed that the print head is now randomly stopping every few layers for about 2-3 seconds, causing blobs on the surface. I put the original timelapse.py back to test, and it is still stopping.
I re-sliced the file without the timelapse gcode in the machine before layer change box, and still stopping.
Uninstalled fluidd, moonraker and nginx and the moonraker timelapse and re-installed all. Still stopping.
Not sure why it started doing that now, I dont think it would have been from the timelapse file, since putting the original back, and uninstalling/re-installing fluidd/moonraker did not work.
I did notice that in the system tab, it looks like Klipper load and MCU RPI load are alot higher than normal.
 
<img width="876" alt="Screenshot 2023-10-02 at 10 55 31 AM" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/3354f0f9-1e6e-453a-b226-463154a3a80a">

I am currently factory resetting and will test again once done.

**Comment by Guilouz** [comment]
The only difference in two files, is the first use h264 encoding and the mast mjpg.

**Comment by BrianP525** [comment]
I think my pausing issue is something else. I have downgraded firmware at this point and it is still doing it. I am leaning towards the file itself at this point.
As far as the timelapse, it works much better, but is there any way to increase the render quality? I took a look through that file, but didn't see a way to adjust quality.

**Comment by Guilouz** [comment]
You can change render settings:

![image](https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/12702322/548b5d31-f330-4b4f-b451-0a9ba003163f)

**Comment by BrianP525** [comment]
I tried with setting Constant Rate Factor to 0 (which is supposed to be max quality) and 51, and dont see much difference. The render set to 0 is 6 bytes larger.
I'm not sure if you can see the video clips uploaded since they wont play here, but I grabbed a screenshot of what I am seeing. Both have large block-texture visible.
Constant Rate Factor set to 51:
<img width="1279" alt="Screenshot 2023-10-02 at 3 23 46 PM" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/68fe78a9-5e52-48a4-a199-0df1f38c5d38">
Constant Rate Factor set to 0:
<img width="1280" alt="Screenshot 2023-10-02 at 3 23 24 PM" src="https://github.com/Guilouz/Creality-K1-and-K1-Max/assets/146669611/a701abb5-338d-4c45-af1a-708f82457405">

**Comment by Guilouz** [comment]
I have improved timelapse render quality by improving bitrate.

**Comment by le-pet** [comment]
i try in the journey, thanks! :)
